# Generated by Django 5.2 on 2025-04-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_letter_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
