# Generated by Django 5.2 on 2025-04-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_letter_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
